### ISSUE TITLE
Shelve Sets

### ISSUE THREAD

**Issue by rastographics** [Breeze/temphire.angular2#2]
Just found this repo and cannot thank you enough for doing this, it is a tremendous help trying to integrate breeze to angular2 for me.

Can you explain what the use case is for the shelveSets in UnitofWork? Is it to be used to make it easier to save multiple sets of entities to disk? I have a really messy solution I made for handling that right now, and your shelveSets looks much more elegant, but I don't understand fully how to use it.

Thanks

**Comment by marcelgood** [comment]
The shelvesets have currently no use case in TempHire. It's something I developed for another project. I may remove it from TempHire. But the use case for it is to be able to park the data in the current unit of work and retrieve it back later. For example if you are building an MDI (Multi Document Interface) type UI you can switch easily between the dataset for one document vs another. For example if TempHire were to allow you to open multiple StaffingResource details at the same time, then the shelveset would be used to manage the data for all the details and switch between them as the user navigates around. 

Angular 2 destroys components and creates components on its own terms, so we have to keep state in services and the shelvesets is a way to keep your entities around in memory while the user is on another screen and then bring them back. It could also help you to write datasets off to disk for offline use and retrieve them back later. 

So for example, I can setup a canDeactivate guard and shelve the current data in the unit of work before the use navigates away from the current route.

```
    canDeactivate(): Observable<boolean> | Promise<boolean> | boolean {
        return promptToSaveIfHasChanges(this.unitOfWork, this.dialogService, this.busyService)
            .then(result => {
                if (result) {
                    // Shelve the current data
                    this.unitOfWork.shelve(shelveKey(this.reportId));
                }

                return result;
            });
    }
```

and then in ngOnInit or a resolver or wherever I load the data when navigating back to the same entity. I unshelve the data and then load the entity from cache instead of going back to the server. The part that you have to think about is when to delete the shelveset. In the application I used it, that happens when the user closes the tab that displays the data. 

```
    resolve(route: ActivatedRouteSnapshot): Observable<any> | Promise<any> | any {
        let staffingResourceId = route.params['id'];

        // Restore shelved data if available and load entity from cache or server
        this.unitOfWork.clear();
        this.unitOfWork.unshelve(shelveKey(staffingResourceId));

        let url = this.router.url;
        return this.busyService.busy(this.unitOfWork.staffingResources.withId(staffingResourceId, true).then(data => {
            if (data) {
                return data;
            } else {
                return this.notFound(url);
            }
        }));
    }
```

**Comment by rastographics** [comment]
Super helpful. Thanks.
